# Generated by Django 3.1.1 on 2020-11-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_product_sixe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sixe',
            new_name='size',
        ),
    ]
